[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["network-programming", "game-development", "wasm", "web-programming"]
description = "Bevy asset loader that transparently supports loading over http(s)"
edition = "2021"
keywords = ["gamedev", "networking", "wasm", "bevy"]
license = "MIT OR Apache-2.0"
name = "bevy_web_asset"
repository = "https://github.com/johanhelsing/bevy_web_asset"
version = "0.6.0"

[dependencies]
bevy = {version = "0.11", default-features = false, features = ["bevy_asset"]}

# Copied from https://github.com/bevyengine/bevy/blob/main/crates/bevy_asset/Cargo.toml
crossbeam-channel = "0.5.0"
notify = "5.0.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
surf = {version = "2.3", default-features = false, features = ["h1-client-rustls"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = {version = "0.3", default-features = false}
wasm-bindgen = {version = "0.2", default-features = false}
wasm-bindgen-futures = "0.4"
web-sys = {version = "0.3.22", default-features = false}

[dev-dependencies]
bevy = {version = "0.10", default-features = false, features = [
  "bevy_asset",
  "bevy_core_pipeline",
  "bevy_sprite",
  "png",
  "x11", # GitHub Actions runners don't have libxkbcommon installed, so can't use Wayland
]}
